### ISSUE TITLE
500 INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by humazed** [MuhammadSaeedBatikh/TyyarGAE#4]
When I'm trying to call any API method I get this strange error.

` com.google.api.client.googleapis.json.GoogleJsonResponseException: 500 Internal Server Error
                                                                         <html>
                                                                         <head>
                                                                         <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
                                                                         <title>Error 500 INTERNAL_SERVER_ERROR</title>
                                                                         </head>
                                                                         <body><h2>HTTP ERROR 500</h2>
                                                                         <p>Problem accessing /_ah/api/orderAPI/v1/sendNotificationByRegToken. Reason:
                                                                         <pre>    INTERNAL_SERVER_ERROR</pre></p><h3>Caused by:</h3><pre>java.io.EOFException
                                                                             at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268)
                                                                             at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
                                                                             at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
                                                                             at java.util.zip.GZIPInputStream.&lt;init&gt;(GZIPInputStream.java:79)
                                                                             at java.util.zip.GZIPInputStream.&lt;init&gt;(GZIPInputStream.java:91)
                                                                             at com.google.api.server.spi.tools.devserver.ApiServlet.getBodyInputStream(ApiServlet.java:173)
                                                                             at com.google.api.server.spi.tools.devserver.RestApiServlet$LilyRequestMarshaller.createBackendRequestBody(RestApiServlet.java:74)
                                                                             at com.google.api.server.spi.tools.devserver.RestApiServlet$LilyRequestMarshaller.marshall(RestApiServlet.java:63)
                                                                             at com.google.api.server.spi.tools.devserver.RestApiServlet$LilyRequestMarshaller.access$100(RestApiServlet.java:58)
                                                                             at com.google.api.server.spi.tools.devserver.RestApiServlet.marshallRequest(RestApiServlet.java:106)
                                                                             at com.google.api.server.spi.tools.devserver.ApiServlet.doSingleBackendCall(ApiServlet.java:311)
                                                                             at com.google.api.server.spi.tools.devserver.RestApiServlet.service(RestApiServlet.java:131)
                                                                             at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
                                                                             at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
                                                                             at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
                                                                             at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
                                                                             at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
                                                                             at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
                                                                             at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
                                                                             at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:128)
                                                                             at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
                                                                             at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
                                                                             at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
                                                                             at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
                                                                             at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
                                                                             at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50)
                                                                             at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
                                                                             at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125)
                                                                             at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
                                                                             at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
                                                                             at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
                                                                             at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
                                                                             at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
                                                                             at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
                                                                             at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
                                                                             at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
                                                                             at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
                                                                             at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)`

**Comment by MuhammadSaeedBatikh** [comment]
convert all endpoint methods to GET not POST
check why that doesn't work later
